### ISSUE TITLE
The requested resource does not exist

### ISSUE THREAD

**Issue by gnakan** [electricimp/Salesforce#11]
Data is not being sent from device to Salesforce. Keep seeing this message in impCentral logs: 
`ERROR: [ { "message": "The requested resource does not exist", "errorCode": "NOT_FOUND" } ]`

Ran through the tutorial twice to double-check the spelling, casing, etc. Consumer Key and Secret have been double-checked. READING_EVENT_NAME is set to "Smart_Fridge_Reading__e"

**Comment by eltoroit** [comment]
Are you still having this issue? I believe the problem is not in the file, but in your project. The error happens when the Platform Event is not found. Did you check the spelling of the platform event? Did you check the CONSUMER_KEY and CONSUMER_SECRET to ensure you are logging into the right Org? Try workbench and see if you can query it, or Apex to see if you can create it.

**Comment by lau-miky** [comment]
It's been a long but I recently had the same problem. I'm using the REST API, and was trying to retreive the leads. In my case the problem was the API version set on the url. I was using the v52.0 since it's the one used in the current documentation. Although, after querying the salesforce API versions I realised that this version isn't enabled yet. So, try to send the data to an earlier version. I hope it works!

**Comment by vimalgandhi** [comment]
It's been a long but I recently had the same problem today. I'm using the Fastapi  API, but I found when I use v56 that time shows an error and when I use v52 that time works fine.
